dist: bionic

services:
  - postgresql
addons:
  postgresql: 10

language: go
go:
- 1.12.x
# Force-enable Go modules. This will be unnecessary when Go 1.14 lands.
env: GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

# Install buffalo
before_script:
  - wget https://github.com/gobuffalo/buffalo/releases/download/v0.15.1/buffalo_0.15.1_linux_amd64.tar.gz
  - tar -xvzf buffalo_0.15.1_linux_amd64.tar.gz
  - sudo mv buffalo /usr/local/bin/buffalo

script:
  - go vet ./...
  - buffalo test
  - yarn install --no-progress
  - yarn test
  - buffalo build --static